micronaut:
  application:
    name: demo

  server:
    port: 8080
    
datasources:
  default:
    url: jdbc:h2:mem:testDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: create_drop
    dialect: H2
jpa:
  default:
    packages-to-scan:
      - 'com.example'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      enabled: true


